# Generated by Django 6.0.5 on 2026-05-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_method',
            field=models.CharField(default='Позвонить мне', max_length=50, verbose_name='Способ связи'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Имя клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Телефон'),
        ),
    ]
