# Generated by Django 6.0.5 on 2026-05-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_contact_method_order_name_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_link',
            field=models.URLField(blank=True, default='', max_length=3000, verbose_name='Ссылка на корзину'),
        ),
    ]
