# Generated by Django 6.0.5 on 2026-05-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_cart_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата мероприятия'),
        ),
        migrations.AddField(
            model_name='order',
            name='guests',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Количество гостей'),
        ),
    ]
