# Generated by Django 6.0.5 on 2026-05-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_event_date_order_guests'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', help_text='Без символа @. Например: ivan_manager', max_length=150, verbose_name='Username в Telegram')),
                ('phone', models.CharField(blank=True, default='', help_text='Например: +79991234567', max_length=30, verbose_name='Номер телефона')),
                ('chat_id', models.CharField(blank=True, default='', help_text='Заполняется автоматически при подключении пользователя в боте', max_length=50, verbose_name='Telegram Chat ID')),
                ('is_active', models.BooleanField(default=True, help_text='Если снято, пользователь перестанет получать уведомления', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Подписчик Telegram',
                'verbose_name_plural': 'Подписчики Telegram',
            },
        ),
    ]
