# Generated by Django 6.0.5 on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_telegramsubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Адрес электронной почты для получения уведомлений', max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, default='', help_text='Опционально (например: Менеджер Иван)', max_length=150, verbose_name='Имя владельца')),
                ('is_active', models.BooleanField(default=True, help_text='Если снято, на этот адрес не будут приходить уведомления', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Подписчик Email',
                'verbose_name_plural': 'Подписчики Email',
            },
        ),
    ]
