# Generated by Django 6.0.5 on 2026-08-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_bot_proxy', models.CharField(blank=True, default='', help_text='URL или строка прокси (например: socks5://user:pass@host:port, http://user:pass@host:port или host:port:user:pass)', max_length=500, verbose_name='Прокси для Telegram-бота')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки системы',
                'verbose_name_plural': 'Настройки системы',
            },
        ),
    ]
