# Generated by Django 6.0.5 on 2026-09-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='sitemap_cache_minutes',
            field=models.PositiveIntegerField(default=0, help_text='0 — генерация на лету (force-dynamic). Значение > 0 (например, 30 или 60) — кэширование на указанное количество минут.', verbose_name='Кэширование sitemap (мин)'),
        ),
    ]
