# Generated by Django 6.0.5 on 2026-09-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0002_systemsettings_sitemap_cache_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='default_from_email',
            field=models.CharField(blank=True, default='', help_text='Отображаемый адрес отправителя. Если пусто, совпадает с Email / Логином SMTP.', max_length=255, verbose_name='Email отправителя (From)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_host',
            field=models.CharField(blank=True, default='', help_text='Например: smtp.yandex.ru. Если не заполнено, берется из .env.', max_length=255, verbose_name='SMTP Сервер (Хост)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_host_password',
            field=models.CharField(blank=True, default='', help_text='Пароль приложения для почты (например, созданный в Яндекс ID). Если не заполнено, берется из .env.', max_length=255, verbose_name='Пароль приложения SMTP'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_host_user',
            field=models.CharField(blank=True, default='', help_text='Почтовый ящик для отправки (например: chef-meal@yandex.com). Если не заполнено, берется из .env.', max_length=255, verbose_name='Email / Логин SMTP'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_port',
            field=models.PositiveIntegerField(default=465, help_text='Обычно 465 для SSL или 587 для TLS.', verbose_name='Порт SMTP'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_use_ssl',
            field=models.BooleanField(default=True, verbose_name='Использовать SSL'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_use_tls',
            field=models.BooleanField(default=False, verbose_name='Использовать TLS'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='frontend_url',
            field=models.CharField(blank=True, default='http://127.0.0.1:3000', help_text='Адрес фронтенда для отправки вебхуков сброса кэша (локально: http://127.0.0.1:3000, на проде: https://chefmil-furshet.ru).', max_length=255, verbose_name='URL фронтенда (Next.js)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='revalidation_secret',
            field=models.CharField(blank=True, default='catering_schema_secret_key_2026', help_text='Секретный токен для авторизации запросов сброса кэша Next.js (REVALIDATION_SECRET).', max_length=255, verbose_name='Секретный ключ вебхука'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='site_url',
            field=models.CharField(blank=True, default='https://chefmil-furshet.ru', help_text='Используется для формирования ссылок на сайт и карточки в админке в уведомлениях.', max_length=255, verbose_name='Основной адрес сайта'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', help_text='Токен бота от @BotFather (например: 123456789:ABCdefGHI...). Если не заполнено, берется из .env.', max_length=255, verbose_name='Токен Telegram-бота'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='telegram_bot_proxy',
            field=models.CharField(blank=True, default='', help_text='URL или строка прокси (например: socks5://user:pass@host:port, http://user:pass@host:port или host:port:user:pass).', max_length=500, verbose_name='Прокси для Telegram-бота'),
        ),
    ]
