# Generated by Django 6.0.5 on 2026-09-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0003_systemsettings_default_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='enable_debug_json_file',
            field=models.BooleanField(default=False, help_text='При включении создает и обновляет файл schema_markup_debug.json в корне проекта при переходе по страницам. По умолчанию выключено для исключения лишней нагрузки на диск.', verbose_name='Генерация JSON файла микроразметки для деф-режима'),
        ),
    ]
