# Generated by Django 6.0.5 on 2026-09-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0004_systemsettings_enable_debug_json_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(blank=True, default='Шеф Мил Фуршет | Доставка фуршетов и кейтеринга в Набережных Челнах', help_text='Заголовок главной страницы в браузере (рекомендуется 50–60 символов). Если пусто — используется системный шаблон.', max_length=255, verbose_name='Title главной страницы (/)')),
                ('home_description', models.TextField(blank=True, default='Заказать кейтеринг, банкетные и фуршетные блюда с доставкой в Набережных Челнах. Вкусные закуски, брускетты, канапе и готовые наборы на любой праздник от Шеф Мил Фуршет.', help_text='Мета-описание главной страницы для поисковиков (рекомендуется 140–160 символов).', verbose_name='Description главной страницы (/)')),
                ('blog_title', models.CharField(blank=True, default='Блог о кейтеринге и фуршетах — статьи и советы | Шеф Мил Фуршет', help_text='Заголовок страницы со списком статей блога (рекомендуется 50–60 символов).', max_length=255, verbose_name='Title страницы блога (/blog)')),
                ('blog_description', models.TextField(blank=True, default='Советы шеф-повара по расчёту фуршета, сервировке стола, подбору гастробоксов и организации кейтеринга на праздник в Набережных Челнах. Читайте в блоге Шеф Мил!', help_text='Мета-описание страницы блога для поисковиков (рекомендуется 140–160 символов).', verbose_name='Description страницы блога (/blog)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки SEO',
                'verbose_name_plural': 'Настройки SEO',
            },
        ),
    ]
