# Generated by Django 6.0.5 on 2026-05-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Доп. услуга',
                'verbose_name_plural': 'Доп. услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Формат мероприятия',
                'verbose_name_plural': 'Форматы мероприятий',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MenuRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=100, verbose_name='Формат мероприятия')),
                ('guests', models.PositiveIntegerField(verbose_name='Количество гостей')),
                ('date', models.DateField(verbose_name='Дата мероприятия')),
                ('food_preferences', models.JSONField(blank=True, default=list, help_text='Список строк: ["Супы, бульоны", "Горячее", ...]', verbose_name='Предпочтения по блюдам')),
                ('additional_services', models.JSONField(blank=True, default=list, help_text='Список ID услуг: ["1", "2", ...]', verbose_name='Дополнительные услуги')),
                ('name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('consent', models.BooleanField(default=True, verbose_name='Согласие с политикой')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('processing', 'В обработке'), ('done', 'Выполнена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Заметки менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Заявка на меню',
                'verbose_name_plural': 'Заявки на меню',
                'ordering': ['-created_at'],
            },
        ),
    ]
