# Generated by Django 6.0.5 on 2026-05-15 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('menu_requests', '0002_alter_menurequest_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='linked_product',
            field=models.ForeignKey(blank=True, help_text="Товар, который откроется при клике на 'узнать подробнее'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_services', to='catalog.product', verbose_name='Связанный товар'),
        ),
    ]
