# Generated by Django 6.0.5 on 2026-05-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_requests', '0003_additionalservice_linked_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='menurequest',
            name='contact_method',
            field=models.CharField(default='Позвонить мне', max_length=50, verbose_name='Способ связи'),
        ),
    ]
