# Generated by Django 5.0.6 on 2026-05-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_requests', '0004_menurequest_contact_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menurequest',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата мероприятия'),
        ),
    ]
