# Generated by Django 6.0.5 on 2026-09-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_requests', '0005_alter_menurequest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='menurequest',
            name='budget',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Примерный бюджет'),
        ),
    ]
