# Generated by Django 6.0.5 on 2026-09-12 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_requests', '0006_menurequest_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(default='⚡ Бесплатный расчет за 15 минут', help_text='Короткий бейдж над заголовком (например: ⚡ Бесплатный расчет за 15 минут)', max_length=150, verbose_name='Бейдж в шапке')),
                ('hero_title', models.CharField(default='Рассчитать меню кейтеринга и банкета в Набережных Челнах', max_length=255, verbose_name='Заголовок страницы (H1)')),
                ('hero_description', models.TextField(default='Укажите формат события, количество персон и пожелания - бесплатно составим персональное меню и смету под ваш бюджет.', verbose_name='Подзаголовок / описание страницы')),
                ('seo_title', models.CharField(blank=True, default='Рассчитать меню кейтеринга онлайн - Бесплатный расчет банкета и фуршета | Шеф Мил', help_text='Оставьте пустым для значения по умолчанию', max_length=255, verbose_name='SEO Заголовок (Meta Title)')),
                ('seo_description', models.TextField(blank=True, default='Бесплатный онлайн-расчёт меню кейтеринга под формат мероприятия, количество гостей и бюджет в Набережных Челнах. Персональная смета за 15 минут!', help_text='Оставьте пустым для значения по умолчанию', verbose_name='SEO Описание (Meta Description)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройка страницы расчёта',
                'verbose_name_plural': 'Настройка страницы расчёта',
            },
        ),
        migrations.AlterModelOptions(
            name='menurequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на расчёт меню', 'verbose_name_plural': 'Заявки на расчёт меню'},
        ),
        migrations.CreateModel(
            name='CalculateFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='menu_requests.calculatepagesettings', verbose_name='Настройки страницы')),
            ],
            options={
                'verbose_name': 'Вопрос FAQ',
                'verbose_name_plural': 'Вопросы FAQ',
                'ordering': ['order'],
            },
        ),
    ]
