# Generated by Django 6.0.5 on 2026-09-12 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_requests', '0008_populate_calculate_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalservice',
            options={'ordering': ['order'], 'verbose_name': 'Доп. услуга', 'verbose_name_plural': 'Дополнительные услуги'},
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='settings',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_services', to='menu_requests.calculatepagesettings', verbose_name='Настройки страницы'),
        ),
        migrations.AddField(
            model_name='calculatepagesettings',
            name='faq_subtitle',
            field=models.CharField(default='Ответы на популярные вопросы о подборе блюд, сроках и сервировке', max_length=255, verbose_name='Подзаголовок блока FAQ'),
        ),
        migrations.AddField(
            model_name='calculatepagesettings',
            name='faq_title',
            field=models.CharField(default='Часто задаваемые вопросы о расчете меню', max_length=150, verbose_name='Заголовок блока FAQ'),
        ),
        migrations.AddField(
            model_name='calculatepagesettings',
            name='steps_subtitle',
            field=models.CharField(default='Прозрачный и комфортный процесс подготовки вашего праздничного стола', max_length=255, verbose_name='Подзаголовок блока шагов'),
        ),
        migrations.AddField(
            model_name='calculatepagesettings',
            name='steps_title',
            field=models.CharField(default='Как мы работаем', max_length=150, verbose_name='Заголовок блока шагов'),
        ),
        migrations.AlterField(
            model_name='calculatepagesettings',
            name='hero_badge',
            field=models.CharField(default='⚡ Бесплатный расчет за 15 минут', help_text='Короткий бейдж над заголовком', max_length=150, verbose_name='Бейдж в шапке'),
        ),
        migrations.CreateModel(
            name='CalculateBudgetOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Опция бюджета')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='budget_options', to='menu_requests.calculatepagesettings', verbose_name='Настройки страницы')),
            ],
            options={
                'verbose_name': 'Опция бюджета',
                'verbose_name_plural': 'Опции примерного бюджета',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CalculateFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='⏱️', max_length=20, verbose_name='Иконка / Эмодзи')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='menu_requests.calculatepagesettings', verbose_name='Настройки страницы')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества (карточки под хиро)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CalculateFoodOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Вид блюда')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_options', to='menu_requests.calculatepagesettings', verbose_name='Настройки страницы')),
            ],
            options={
                'verbose_name': 'Вид блюда',
                'verbose_name_plural': 'Виды блюд (предпочтения)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CalculateStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(default='01', max_length=10, verbose_name='Номер шага (01, 02...)')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок шага')),
                ('text', models.TextField(verbose_name='Описание шага')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='menu_requests.calculatepagesettings', verbose_name='Настройки страницы')),
            ],
            options={
                'verbose_name': 'Шаг процесса',
                'verbose_name_plural': 'Шаги процесса («Как мы работаем»)',
                'ordering': ['order'],
            },
        ),
    ]
