# Generated by Django 6.0.5 on 2026-09-08 21:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0011_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок статьи')),
                ('slug', models.SlugField(blank=True, help_text='Если не заполнено, генерируется автоматически из заголовка', max_length=255, unique=True, verbose_name='URL-слаг')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='blog/covers/', verbose_name='Обложка')),
                ('is_cover_like_block_image', models.BooleanField(default=False, verbose_name='Сделать обложку как картинку из блока статьи')),
                ('cover_alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt-текст обложки')),
                ('cover_source_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на источник обложки')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Статьи блога',
                'ordering': ['-created_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Связанный товар / сет')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_products', to='blog.blogarticle', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Товар из статьи',
                'verbose_name_plural': 'Товары из статьи',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogArticleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='Изображение в статье')),
                ('image_alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt-текст изображения')),
                ('image_source_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на источник изображения')),
                ('image_height_unlimited', models.BooleanField(default=False, verbose_name='Не ограничивать по высоте')),
                ('text', models.TextField(blank=True, help_text='Инструкция по форматированию текста:<br/>• <b>Заголовок блока</b>: выделите строку одной звездочкой с двух сторон. Пример: <code>*Введение*</code><br/>• <b>Акцентный блок (карточка)</b>: выделите текст двумя звездочками с двух сторон. Пример:<br/><code>**Это важный текст<br/>на две строки**</code><br/>• <b>Жирный текст</b>: выделите текст двумя символами подчёркивания с двух сторон. Пример: <code>__это жирный текст__</code><br/>• <b>Ссылки</b>: используйте стандартный HTML-тег ссылки. Пример: <code>&lt;a href="https://..." target="_blank"&gt;Текст&lt;/a&gt;</code><br/>• <b>Списки</b>: начните строку с символов \'&gt;1. \', \'&gt;2. \' и т.д. Пример:<br/><code>&gt;1. Первый пункт<br/>&gt;2. Второй пункт</code><br/>• <b>Обычный текст</b>: пишется без специальных символов. Пустые строки создают абзацные отступы.', verbose_name='Текст блока')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='blog.blogarticle', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Блок статьи',
                'verbose_name_plural': 'Блоки статьи',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RelatedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_articles_association', to='blog.blogarticle', verbose_name='Статья')),
                ('related_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogarticle', verbose_name='Связанная статья')),
            ],
            options={
                'verbose_name': 'Связанная статья',
                'verbose_name_plural': 'Связанные статьи',
                'ordering': ['order'],
            },
        ),
    ]
