# Generated by Django 6.0.5 on 2026-05-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('inn', models.CharField(blank=True, default='', max_length=20, verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, default='', max_length=20, verbose_name='ОГРН')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telegram', models.URLField(blank=True, default='', max_length=300, verbose_name='Telegram')),
                ('max_messenger', models.URLField(blank=True, default='', max_length=300, verbose_name='MAX мессенджер')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name='Минимальная сумма заказа (₽)')),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=10000, max_digits=10, verbose_name='Порог бесплатной доставки (₽)')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=1500, max_digits=10, verbose_name='Стоимость доставки (₽)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
    ]
