# Generated by Django 6.0.5 on 2026-05-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='reviews_url',
            field=models.URLField(blank=True, default='', max_length=1000, verbose_name='Ссылка на отзывы (Авито)'),
        ),
    ]
