# Generated by Django 6.0.5 on 2026-05-16 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('company', '0002_companyinfo_reviews_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Текст ссылки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_navs', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Навигация в футере',
                'verbose_name_plural': 'Навигация в футере',
                'ordering': ['order', 'name'],
            },
        ),
    ]
