# Generated by Django 6.0.5 on 2026-05-17 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_footernavigation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footernavigation',
            options={'ordering': ['order', 'category__name'], 'verbose_name': 'Навигация в футере', 'verbose_name_plural': 'Навигация в футере'},
        ),
        migrations.RemoveField(
            model_name='footernavigation',
            name='name',
        ),
    ]
