# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_footernavigation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='hero_image_bottom',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Изображение для хиро-секции (нижнее)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_image_top',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Изображение для хиро-секции (верхнее)'),
        ),
    ]
