# Generated by Django 6.0.5 on 2026-05-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companyinfo_hero_image_bottom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='hero_image_top_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Изображение для хиро-секции (верхнее, мобильное)'),
        ),
    ]
