# Generated by Django 6.0.5 on 2026-09-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companyinfo_hero_image_top_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=55.743821, help_text='Географическая широта для карт и Schema.org (например: 55.743821)', max_digits=9, verbose_name='Широта (latitude)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=52.408215, help_text='Географическая долгота для карт и Schema.org (например: 52.408215)', max_digits=9, verbose_name='Долгота (longitude)'),
        ),
    ]
