# Generated by Django 6.0.5 on 2026-09-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_companyinfo_latitude_companyinfo_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='city',
            field=models.CharField(default='Набережные Челны', help_text='Город для Schema.org PostalAddress (addressLocality)', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='legal_name',
            field=models.CharField(blank=True, default='', help_text='Официальное юр. лицо (например: ИП или ООО). Если пусто, используется название компании.', max_length=200, verbose_name='Юридическое название'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='price_range',
            field=models.CharField(blank=True, default='₽₽', help_text='Для Schema.org (например: ₽₽)', max_length=50, verbose_name='Ценовой диапазон'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='serves_cuisine',
            field=models.CharField(blank=True, default='Кейтеринг, Фуршетные сеты, Закуски, Гастробоксы, Канапе, Брускетты', help_text='Через запятую для Schema.org servesCuisine', max_length=500, verbose_name='Кухни / направления блюд'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vk',
            field=models.URLField(blank=True, default='', max_length=300, verbose_name='ВКонтакте'),
        ),
    ]
