# Generated by Django 6.0.5 on 2026-09-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_companyinfo_city_companyinfo_legal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Город для Schema.org PostalAddress (addressLocality)', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Географическая широта для карт и Schema.org (например: 55.743821). Если не заполнено, geo-блок не выводится.', max_digits=9, null=True, verbose_name='Широта (latitude)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='legal_name',
            field=models.CharField(blank=True, default='', help_text='Официальное юр. лицо (например: ИП или ООО). Если пусто, в разметке используется название компании.', max_length=200, verbose_name='Юридическое название'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Географическая долгота для карт и Schema.org (например: 52.408215). Если не заполнено, geo-блок не выводится.', max_digits=9, null=True, verbose_name='Долгота (longitude)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='price_range',
            field=models.CharField(blank=True, default='', help_text='Для Schema.org (например: ₽₽). Если пусто, не выводится.', max_length=50, verbose_name='Ценовой диапазон'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='serves_cuisine',
            field=models.CharField(blank=True, default='', help_text='Через запятую для Schema.org servesCuisine. Если пусто, не выводится.', max_length=500, verbose_name='Кухни / направления блюд'),
        ),
    ]
