# Generated by Django 6.0.5 on 2026-09-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_legaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='rkn_registry_number',
            field=models.CharField(blank=True, default='', help_text='Определяется автоматически из ссылки (например: 16-25-059794), либо можно указать вручную.', max_length=100, verbose_name='Номер в реестре РКН'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='rkn_registry_url',
            field=models.URLField(blank=True, default='', help_text='Ссылка на запись в реестре РКН (например: https://pd.rkn.gov.ru/operators-registry/operators-list/?id=16-25-059794)', max_length=1000, verbose_name='Реестр операторов Роскомнадзора (ссылка)'),
        ),
    ]
