# Generated by Django 6.0.5 on 2026-09-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_companyinfo_rkn_registry_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Основное изображение Open Graph для отображения ссылки на сайт в Telegram, VK, WhatsApp и поисковиках. Рекомендуется соотношение 1.91:1 (например, 1200x630 px). Используется на всех страницах сайта, кроме карточек товаров и отдельных статей блога.', null=True, upload_to='company/', verbose_name='Изображение для соцсетей (OG Image)'),
        ),
    ]
