# Generated by Django 6.0.5 on 2026-05-14 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Используется как фильтр в каталоге (например: profitable, desserts)', max_length=100, unique=True, verbose_name='Идентификатор (slug)')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('image_url', models.URLField(blank=True, default='', max_length=500, verbose_name='URL изображения (внешний)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение (загружаемое)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (₽)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Заполните, если хотите показать зачёркнутую цену', max_digits=10, null=True, verbose_name='Старая цена (₽)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_featured', models.BooleanField(default=False, help_text="Отображается в разделе 'Выгодно'", verbose_name='Рекомендуемый')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество/вес')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_info', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Доп. информация',
                'verbose_name_plural': 'Доп. информация',
                'ordering': ['order'],
            },
        ),
    ]
