# Generated by Django 6.0.5 on 2026-05-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_order_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Минимальное количество товара для заказа. Если пусто, ограничений нет.', null=True, verbose_name='Минимальное количество заказа'),
        ),
    ]
