# Generated by Django 6.0.5 on 2026-06-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_min_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='min_order_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Минимальное количество товара для заказа этого варианта. Если пусто, используется ограничение продукта.', null=True, verbose_name='Минимальное количество заказа'),
        ),
    ]
