# Generated by Django 6.0.5 on 2026-08-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_section_category_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='section',
        ),
        migrations.AddField(
            model_name='section',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Выберите категории, входящие в этот раздел', related_name='sections', to='catalog.category', verbose_name='Категории'),
        ),
    ]
