# Generated by Django 6.0.5 on 2026-08-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_category_section_section_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sections/', verbose_name='Изображение (загружаемое)'),
        ),
        migrations.AddField(
            model_name='section',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URL изображения (внешний)'),
        ),
    ]
