# Generated by Django 6.0.5 on 2026-09-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_sectioncategory_through'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Используется как фильтр в каталоге (например: profitable, desserts). Если оставить пустым, сгенерируется из названия.', max_length=100, unique=True, verbose_name='Идентификатор (slug)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(blank=True, help_text='Используется как фильтр раздела (например: furshet, banquet). Если оставить пустым, сгенерируется из названия.', max_length=100, unique=True, verbose_name='Идентификатор (slug)'),
        ),
    ]
