# Generated by Django 6.0.5 on 2026-09-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_category_slug_alter_section_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Используется в URL карточки товара. Если оставить пустым, сгенерируется из названия.', max_length=300, null=True, unique=True, verbose_name='Идентификатор (slug)'),
        ),
    ]
