# Generated by Django 6.0.5 on 2026-09-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='seo_description',
            field=models.TextField(blank=True, default='', help_text='Оставьте пустым для автогенерации по формуле с перечислением категорий раздела', verbose_name='SEO Описание (Description)'),
        ),
        migrations.AddField(
            model_name='section',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='Оставьте пустым для автогенерации (например: Фуршетные блюда и закуски — заказать с доставкой в Набережных Челнах)', max_length=255, verbose_name='SEO Заголовок (Title)'),
        ),
    ]
